{
  "formatVersion": "1.1",
  "component": {
    "group": "org.gradle",
    "module": "example-dependency",
    "version": "6.2.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2-20200107194018+0000",
      "buildId": "nz5y2wynkzdp3mvmynpcm3geay"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "minified": true,
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "example-dependency-6.2.2.jar",
          "url": "example-dependency-6.2.2.jar",
          "size": 946,
          "sha512": "0eecd21158c25341ed939c7ff84a770e8a9a37846ae4fd9e7fd96038180b4bccc2ce0b91faf36b247eef7cbe5dcf3eaf942bc39b4d7085faa03e76f213029637",
          "sha256": "f9ba8db1116e9b475398b57add11e69ca7f0291758d1c40683a84921b5939b95",
          "sha1": "551a0d0b4a039706db648064855af32d9addf5db",
          "md5": "bc78b191dd8c68de3e4b99b07c61c8b2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "minified": true,
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "example-dependency-6.2.2.jar",
          "url": "example-dependency-6.2.2.jar",
          "size": 946,
          "sha512": "0eecd21158c25341ed939c7ff84a770e8a9a37846ae4fd9e7fd96038180b4bccc2ce0b91faf36b247eef7cbe5dcf3eaf942bc39b4d7085faa03e76f213029637",
          "sha256": "f9ba8db1116e9b475398b57add11e69ca7f0291758d1c40683a84921b5939b95",
          "sha1": "551a0d0b4a039706db648064855af32d9addf5db",
          "md5": "bc78b191dd8c68de3e4b99b07c61c8b2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "example-dependency-6.2.2-sources.jar",
          "url": "example-dependency-6.2.2-sources.jar",
          "size": 781,
          "sha512": "86be0450bf02393366a99cea33eef2b56413902216016a7a6e5777bf7ced90f0ef219b738ccd999af38d7e3d6a3a4589cc73e7b9073a1b519c7d628e4c99e8cc",
          "sha256": "f132607800cb3e0f701f6e6e99407684cf3c4345cb81231bca18505e5115b044",
          "sha1": "c5b398cc7fbc0b0c81cd791a8b0f9520f3f34c92",
          "md5": "30c0cb84bf113c0065fb929bab929fe1"
        }
      ]
    }
  ]
}
